version: '3'

services:
  myconsul:
    image: progrium/consul
    restart: always
    hostname: consul
    ports:
      - 8500:8500
    command: "-server -bootstrap"

  nodeweb:
    image: keyax/node_core
    depends_on:
      - couchbase
#        condition: service_healthy
    working_dir: /home/node
#    entrypoint: "slc start"
    ports:
      - 80:80
#    links:
#      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    labels:
      net.keyax.www: "keyax web server"
  #  volumes:
    #  - keyax_app: /webapp

  couchbase:
#    image: arungupta/couchbase-node
    image: keyax/couchbase_core
    ports:
      - 8091-8093:8091-8093
#      - 9100-9105:9100-9105
#      - 11207:11207
#      - 11209-11211:11209-11211
#      - 18091-18093:18091-18093
      - 11210:11210
      - 4369:4369
#      - 21100-21299:21100-21299
#    healthcheck:
#      test: ["CMD", "echo", "db.stats().ok", "|", "mongo", "localhost:27017/test"]
#      echo 'db.stats().ok' | mongo 192.168.5.51:30000/test --quiet
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
    labels:
      net.keyax.kyx: "keyax data server"

# networks:
#   default:
#     driver: overlay
